---
dev:
  rgbank:
    dev:
      nodes:
        'Node[rgbankdev.vm]':
          - 'Rgbank::Web'
          - 'Rgbank::Load'
          - 'Rgbank::Db'
staging:
  rgbank:
    staging:
      nodes:
        'Node[appserver01-staging.vm]':
          - 'Rgbank::Web'
        'Node[database-staging.vm]':
          - 'Rgbank::Db'
        'Node[loadbalancer-staging.vm]':
          - 'Rgbank::Load'
production:
  rgbank:
    production:
      nodes:
        'Node[appserver01.vm]':
          - 'Rgbank::Web'
        'Node[appserver02.vm]':
          - 'Rgbank::Web'
        'Node[appserver03.vm]':
          - 'Rgbank::Web'
        'Node[database.vm]':
          - 'Rgbank::Db'
        'Node[loadbalancer.vm]':
          - 'Rgbank::Load'
