---
dev:
  rgbank:
    dev:
      nodes:
        'Node[rgbankdev.vm]':
          - 'Rgbank::Web[dev-0]'
          - 'Rgbank::Load[dev]'
          - 'Rgbank::Db[dev]'
staging:
  rgbank:
    staging:
      nodes:
        'Node[appserver01-staging.vm]':
          - 'Rgbank::Web[dev-0]'
        'Node[database-staging.vm]':
          - 'Rgbank::Db[staging]'
        'Node[loadbalancer-staging.vm]':
          - 'Rgbank::Load[staging]'
production:
  rgbank:
    production:
      web_count: 3
      nodes:
        'Node[appserver01.vm]':
          - 'Rgbank::Web[production-0]'
        'Node[appserver02.vm]':
          - 'Rgbank::Web[production-1]'
        'Node[appserver03.vm]':
          - 'Rgbank::Web[production-2]'
        'Node[database.vm]':
          - 'Rgbank::Db[production]'
        'Node[loadbalancer.vm]':
          - 'Rgbank::Load[production]'
