---
dev:
  rgbank:
    dev-0:
      components:
        ['Rgbank::Web','Rgbank::Db', 'Rgbank::Load']:
          - rgbankdev.vm
staging:
  rgbank:
    staging-0:
      parameters:
        db_username: 'staginguser'
        db_password: 'myawesomepassword'
      components:
        Rgbank::Web:
          - appserver01-staging.vm
        Rgbank::Db:
          - database-staging.vm
        Rgbank::Load:
          - loadbalancer-staging.vm
production:
  rgbank:
    dynamic-allocation:
      parameters:
        dynamic_infrastructure: true
      components:
        Rgbank::Db:
          - database.vm
        Rgbank::Infrastructure::Web:
          - master
        Rgbank::Web
          - rgbank-web-1
    production-phase-1:
      components:
        Rgbank::Web:
          - appserver01.vm
          - appserver02.vm
          - appserver03.vm
        Rgbank::Db:
          - database.vm
        Rgbank::Load:
          - loadbalancer.vm
    production-phase-2:
      components:
        Rgbank::Web:
          - appserver04.vm
    production-phase-3:
      components:
        Rgbank::Web:
          - appserver05.vm
