---
dev:
  rgbank:
    dev-0:
      components:
        ['Rgbank::Web','Rgbank::Db', 'Rgbank::Load']:
          - rgbankdev.vm
staging:
  rgbank:
    staging-0:
      parameters:
        db_username: 'staginguser'
        db_password: 'myawesomepassword'
      components:
        Rgbank::Web:
          - appserver01-staging.vm
        Rgbank::Db:
          - database-staging.vm
        Rgbank::Load:
          - loadbalancer-staging.vm
production:
  rgbank:
    production-dynamic-allocation:
      components:
        Rgbank::Db:
          - database.vm
        Rgbank::Infrastructure::Web[rgbank-web-1]:
          - master
        Rgbank::Web:
          - rgbank-web-1
    production-static:
      components:
        Rgbank::Web:
          - appserver01.vm
          - appserver02.vm
          - appserver03.vm
        Rgbank::Db:
          - database.vm
        Rgbank::Load:
          - loadbalancer.vm
