---
dev:
  rgbank:
    dev-0:
      components:
        ['Rgbank::Web','Rgbank::Db', 'Rgbank::Load']:
          - rgbank-dev.vm
puppetconf_header:
  rgbank:
    dev-0:
      components:
        ['Rgbank::Web','Rgbank::Db', 'Rgbank::Load']:
          - rgbank-dev.pdx.puppet.vm
staging:
  rgbank:
    staging-0:
      parameters:
        db_username: 'staginguser'
        db_password: 'myawesomepassword'
      components:
        Rgbank::Web:
          - rgbank-appserver-01-staging.pdx.puppet.vm
        Rgbank::Db:
          - database-staging.pdx.puppet.vm
        Rgbank::Load:
          - rgbank-staging.pdx.puppet.vm
production:
  rgbank:
    production-static:
      components:
        Rgbank::Web:
          - rgbank-appserver-01.pdx.puppet.vm
          - rgbank-appserver-02.pdx.puppet.vm
          - rgbank-appserver-03.pdx.puppet.vm
        Rgbank::Db:
          - database.pdx.puppet.vm
        Rgbank::Load:
          - rgbank.pdx.puppet.vm
